spring.application.name=database

spring.datasource.url=jdbc:postgresql://localhost:5432/nba_stats_db
spring.datasource.username=nbaplayer_user
spring.datasource.password=lucky
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=3YgGrH7wgfaY5CEXTUaQjD+MF3Y8tTTRAidBR1eFPZY
jwt.expiration=3600000  

server.error.whitelabel.enabled=false
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.mvc.problem-details.enabled=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

server.port=8081